import type { Config } from "tailwindcss";

// Token set transcribed verbatim from the Stitch exports in screens/
// (dashboard.html / lending.html) so the marketing pages and the Phase 3
// dashboards share one design system. Colors are literal hex (matching the
// export) rather than CSS vars, so export markup can be lifted class-for-class.
const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // ---- Fianza.dc.html design system (landing/underwrite/borrower/
        // lender) — literal hex, kept separate from the tokens below so the
        // docs/demo pages (still on the old blue theme) are unaffected. ----
        obsidian: "#0B0F0E",
        void: "#060908",
        bone: "#F4F1E9",
        nectar: "#FFB020",
        ion: "#58F0C8",
        flare: "#FF5C4D",
        ash: "#A7ADA6",

        background: "#0f131c",
        surface: "#0f131c",
        "surface-dim": "#0f131c",
        "surface-bright": "#353943",
        "surface-container-lowest": "#0a0e17",
        "surface-container-low": "#181b25",
        "surface-container": "#1c1f29",
        "surface-container-high": "#262a34",
        "surface-container-highest": "#31353f",
        "surface-variant": "#31353f",
        "on-surface": "#dfe2ef",
        "on-surface-variant": "#c2c6d6",
        "on-background": "#dfe2ef",
        outline: "#8c909f",
        "outline-variant": "#424754",
        "surface-tint": "#adc6ff",
        primary: "#adc6ff",
        "primary-container": "#4d8eff",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc6ff",
        "inverse-primary": "#005ac2",
        "on-primary": "#002e6a",
        "on-primary-container": "#00285d",
        "on-primary-fixed": "#001a42",
        "on-primary-fixed-variant": "#004395",
        secondary: "#4edea3",
        "secondary-container": "#00a572",
        "secondary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary": "#003824",
        "on-secondary-container": "#00311f",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005236",
        tertiary: "#ffb95f",
        "tertiary-container": "#ca8100",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary": "#472a00",
        "on-tertiary-container": "#3e2400",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#dfe2ef",
        "inverse-on-surface": "#2c303a",
      },
      spacing: {
        unit: "4px",
        gutter: "24px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "24px",
        "card-padding": "24px",
        "container-padding-mobile": "16px",
        "container-padding-desktop": "32px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "ui-monospace", "monospace"],
        display: ["var(--font-display)", "var(--font-inter)", "sans-serif"],
        // Fianza.dc.html type system: Spectral (serif, headlines/verdicts),
        // Space Grotesk (grotesk sans — reuses --font-display, already loaded),
        // Space Mono (mono, labels/data).
        "tl-serif": ["var(--font-spectral)", "Georgia", "serif"],
        "tl-sans": ["var(--font-display)", "system-ui", "sans-serif"],
        "tl-mono": ["var(--font-space-mono)", "ui-monospace", "monospace"],
        "display-lg": ["var(--font-display)", "var(--font-inter)"],
        "headline-lg": ["var(--font-display)", "var(--font-inter)"],
        "headline-lg-mobile": ["var(--font-display)", "var(--font-inter)"],
        "headline-md": ["var(--font-display)", "var(--font-inter)"],
        "body-lg": ["var(--font-inter)"],
        "body-md": ["var(--font-inter)"],
        "body-sm": ["var(--font-inter)"],
        "label-caps": ["var(--font-inter)"],
        "data-lg": ["var(--font-mono)"],
        "data-md": ["var(--font-mono)"],
      },
      fontSize: {
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "data-lg": ["18px", { lineHeight: "24px", fontWeight: "500" }],
        "data-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
