services:
  - type: web
    name: trustline-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: SCORE_SIGNER_SECRET
        sync: false
      - key: SCORE_REGISTRY_CONTRACT_ID
        value: CAZUPW5MWHG5XCE7BM6YP6M52NPB6TPRRAXU3GEV4TL2AR2ZMYE7TRSX
      - key: CREDIT_LINE_CONTRACT_ID
        value: CC4ZAKREYMCDEONIQMSSBYOBFC75LL5NPYVEBRZ5SACHYWLYGK2R7GDO
      - key: LENDING_VAULT_CONTRACT_ID
        value: CA7QGIAUGENZU3V63CVUT2N56X3ASZ774E3RCAHFZ2WKAQGOCKTDIQOA
      - key: DEMO_HONEST_AGENT
        value: GB2FTLU3SE6GVATDG2TZMGRYJTRXLZJJM6PKYNZUV3PE6BSATL3PN5L3
      - key: DEMO_SYBIL_AGENT
        value: GAXCQ2B6MLJSP6IHB3DLMARUJMJLWMCEUV5ZMI4OHJ3FZGMYO55F5NLN
      - key: DEMO_FROM_LEDGER
        value: "3369652"
      - key: X402_EXCLUDE_ADDRESSES
        value: GDS55JGUTDAH43XQRQGYK5NTDIO57HFA5OP6EOQ3AZ2E3GG634A2ZD5L,GA6THKUY2XJZOBRFMEQMMEADSCQLCZ2QMQWAWMMDXBTE7SARKAXVH7TL,GA2YSWX54ZNO2E3AC74Q4MJRSH4I5EPBEFD52VSF4WWDHA2NX4YFTUOF,CD5RQFFYF57MLI3JI2PHUROMYFWLGDB7RPMGIK5JRWAO6NWHEUE3EC6C,CA7QGIAUGENZU3V63CVUT2N56X3ASZ774E3RCAHFZ2WKAQGOCKTDIQOA
      - key: SCORE_BAND_DIVISOR
        value: "1000"
      - key: OZ_API_KEY
        sync: false
      - key: FACILITATOR_URL
        value: https://channels.openzeppelin.com/x402/testnet
