#!/usr/bin/env bash
# Phase 4 — wire deployed contract ids into backend/.env (no secrets touched/printed).
cd "$HOME/stellar/backend" || exit 1
sed -i 's#^SCORE_REGISTRY_CONTRACT_ID=.*#SCORE_REGISTRY_CONTRACT_ID=CAZUPW5MWHG5XCE7BM6YP6M52NPB6TPRRAXU3GEV4TL2AR2ZMYE7TRSX#' .env
grep -q '^CREDIT_LINE_CONTRACT_ID=' .env || echo 'CREDIT_LINE_CONTRACT_ID=CA2HOO3KKDPQB4URKDJGVP4QD57UTCSKA2XN7U76RAN4VATOKXZV4QSV' >> .env
grep -q '^LENDING_VAULT_CONTRACT_ID=' .env || echo 'LENDING_VAULT_CONTRACT_ID=CD5RQFFYF57MLI3JI2PHUROMYFWLGDB7RPMGIK5JRWAO6NWHEUE3EC6C' >> .env
echo '--- contract-id lines now in backend/.env ---'
grep -E '^(SCORE_REGISTRY|CREDIT_LINE|LENDING_VAULT)_CONTRACT_ID=' .env
